### ISSUE TITLE
Shoes gems not bundled in jar after the big gem bust-out

### ISSUE THREAD

**Issue by wasnotrice** [shoes/furoshiki#12]
See shoes/shoes4#969.

The jar only contains these gems. Notably missing: `shoes`, `shoes-core`, `shoes-swt`

```
specifications/
specifications/after_do-0.3.1.gemspec
specifications/bundler-1.7.7.gemspec
specifications/furoshiki-0.2.0.gemspec
specifications/jruby-jars-1.7.16.1.gemspec
specifications/jruby-rack-1.1.16.gemspec
specifications/nokogiri-1.6.4.1-java.gemspec
specifications/plist-3.1.0.gemspec
specifications/rake-10.4.2.gemspec
specifications/rubyzip-1.1.6.gemspec
specifications/shoes-highlighter-1.0.0.gemspec
specifications/shoes-manual-4.0.0.gemspec
specifications/swt-4.4.gemspec
specifications/warbler-1.4.4.gemspec
```

**Comment by wasnotrice** [comment]
I thought (though I could be wrong) that in Shoes 3, you can *always* press Cmd-M (or Ctrl-M, I always forget) and see the manual. But maybe not. In any case, I agree, that's not a common use case with a packaged app, and you could always include it in your package (though we should probably at least test that it works). I guess that's more for packaging the Shoes GUI itself.

By .apps, I mean packaging your Shoes app as a Mac application with the extension .app. I mention that only because it has worked in the past.

**Comment by PragTob** [comment]
I'm closing up here as @jasonrclark suggested - we can take the discussion elsewhere I guess. For what it's worth I'm also torn about including the manual by default - it could be worth dropping as it's not a common use case but it IS vintage shoes behavior.
