### ISSUE TITLE
JavaAppLauncher for OSX app does not start correctly

### ISSUE THREAD

**Issue by justahero** [shoes/furoshiki#16]
During the development of a Shoes app I packaged it to run on OSX (10.9.5) with

``` bash
$ shoes -p swt:app app/app.yaml
```

The resulting package could not be started via `open ./path-to/Shoes.app`, it crashes with an OSX report dialog. The following environment is used:
- JRuby 1.7.18 (via rvm)
- shoes gem, version `4.0.0.pre3`
- Java Version "1.8.0_31", Java(TM) SE Runtime Environment (build 1.8.0_31-b13)

From what I understand the packaging mechanism of Shoes uses version `0.3.0` of the furoshiki gem. It downloads a template zip file, containing a jar app and injects all Shoes related stuff into it before finalising it. The [jar app template](https://s3.amazonaws.com/net.wasnotrice.shoes/wrappers/shoes-app-template-0.0.1.zip) contains folders and files, for example `Info.plist` in the root and the `Plugins/1.7.0.jdk` folder contains a bundled Java runtime.
Unfortunately the bundled Java runtime inside the template seems to cause trouble on my system. After a bit of research I found the following [StackOverflow answer](http://stackoverflow.com/questions/24582806/creating-bundle-for-java-7-jar-file-on-macos-manually) to solve my problem. After removing the lines from the `Info.plist` file:

```
<key>JVMRuntime</key>
<string>1.7.0.jdk</string>
```

the application could be opened via `open ./path-to/Shoes.app` successfully. Deleting the `1.7.0.jdk` folder along with it was fine too and reduces the size of the app quite considerably.

**Comment by justahero** [comment]
Seems related to shoes/shoes4#477, the OSX crash report I received looks similar.

**Comment by PragTob** [comment]
Thanks for the detailed report Sebastian! :) 

If I understood Florian correctly this does only happen on systems that don't have a JDK installed?

Any thoughts @wasnotrice ?

packaging is still a fragile little being, we'll see to get it fixed. Thanks!

**Comment by justahero** [comment]
A JDK is installed (`1.8.0_31`), also tested it with the latest Java7 version (`1.7.0_75`) as well, both behave the same.

**Comment by PragTob** [comment]
Advantages of being friends with one of the core developers :) 

Will be hard for me to debug (due to `NoMacException`). I'll try to convince @wasnotrice or @jasonrclark to take a look at this (given the time). We are also happy to receive pull requests of any kind :-)

We probably need @wasnotrice at one point or another either way as the app template is gracefully hosted in is S3 if I remember correctly (and he built major parts of this) :heart:

**Comment by wasnotrice** [comment]
First off, thanks for the bug report @justahero and @PragTob.

No brilliant ideas off the top of my head, but it's been a long while since the contents of the template file were changed, so it wouldn't surprise me that something has gone wrong there. Hoping to get some time soon to look into this. Would be great if we can reduce the app size though!

**Comment by justahero** [comment]
@PragTob, @wasnotrice 

Tried to find a good way to include another JRE in the bundle without too much hassle. On OSX all JDKs are installed into the folder `/Library/Java/JavaVirtualMachines`. After I packaged the Shoes app with `shoes -p swt:app app/app.yaml` I deleted the existing `1.7.0.jdk` folder from the template jar app (in Plugins folder). Then I copied one JDK / JRE from the Library folder and adjusted the `JVMRuntime` string in the `Info.plist` file to contain the name of the copied JDK folder (e.g. `jdk.1.8.0_32.jdk`). Starting the app with `open ./path-tp/Shoes.app` works successfully.

The following commands

```
rm -rf Shoes.app/Contents/PlugIns/1.7.0.jdk
cp -r /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk Shoes.app//Contents/Plugins/
```

removes the previous JRE and copies a new JRE plain to the App.

Not sure why the bundled JRE does not work correctly, but it seems copying another JRE into the bundle does not cause trouble. Still needs further testing, e.g. running the bundled app on a different machine that does not have a JDK installed.

**Comment by PragTob** [comment]
As of #17 we do have a new template - I hope that this has fixed it. @justahero are you willing to recheck from master? :)

Thanks!

**Comment by justahero** [comment]
Will try it again this week.

Get well soon @PragTob!

**Comment by justahero** [comment]
Hey all,

had the chance to check the current version of the furoshiki gem (master) again and bundled a Shoes application with it (4.0.0.pre3). The reported error dialog does not appear anymore, but there is another issue. When the package is moved to the `Applications` folder the following error message appears right after the start of the application.

```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Shoes.app.
```

Interestingly enough, executing the application from inside the `app/pkg` folder of the project works fine, moving it to different folder yields the same error. Tried to fix / adjust permissions with `chown` and the executable bit of the application (& JavaAppLauncher) was set with `chmod`, just to be sure. Tested on OSX 10.9.5.

**Comment by jasonrclark** [comment]
Curious whether it makes any difference running with Shoes master. I was able to move around an app built with that latest combination, and it worked from the other locations.

**Comment by jasonrclark** [comment]
Given the age of this and that we've moved away from using the JavaAppLauncher, I'm going to close this out. If anyone repros, feel free to chime in.
