### ISSUE TITLE
Keep the shoes-app-template as part of furoshiki/separate gem?

### ISSUE THREAD

**Issue by PragTob** [shoes/furoshiki#5]
Right now when packaging a shoes-swt-app furoshiki makes a request to get shoes-app-template-0.0.1.zip from shoesrb.com.

Maybe it would be better to have that gem straight in the shoes gem, the furoshiki gem or somewhere else we can reliably depend upon not the website? Or are there advantages of this I don't see yet?

**Comment by jasonrclark** [comment]
This has changed significantly with the new templates, so I think we're good to go on it.
